name: Deploy DNS Configuration

on:
  pull_request:
    types:
      - closed

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install DNSControl
        run: bin/install-dnscontrol -i

      - name: Preview DNS Changes
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: /usr/local/bin/dnscontrol preview

  push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: preview
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install DNSControl
        run: bin/install-dnscontrol -i

      - name: Push DNS Changes
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: /usr/local/bin/dnscontrol push