name: Preview

on:
  push:
    paths:
      - "dnsconfig.js"
      - "creds.json"
      - ".github/workflows/preview.yml"

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install DNSControl
        run: bin/install-dnscontrol -i

      - name: DNSControl preview
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: /usr/local/bin/dnscontrol preview